4 Django/solutions/mysite/contactsapp/urls.py
from django.urls import path

from . import views

app_name = 'contactsapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('save/', views.save, name='save'),
    path('delete/', views.delete, name='delete')
]

4 Django/solutions/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('todos/', include('todoapp.urls')),
    path('todosajax/', include('todoajax.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('contactcbv/', include('contactcbv.urls'))
]

4 Django/solutions/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

4 Django/solutions/mysite/contactsapp/models.py
from django.db import models
from django.utils import timezone


class Contact(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateTimeField()
    favorite_number = models.FloatField()
    favorite_fruit = models.CharField(max_length=100)
    favorite_color = models.CharField(max_length=100)

    def age(self):
        return (timezone.now() - self.birthday).days//365

    def __str__(self):
        return self.name

4 Django/solutions/mysite/contactsapp/views.py
from django.shortcuts import render, reverse

from django.http import HttpResponse, HttpResponseRedirect



from .models import Contact


def index(request):
    contacts = Contact.objects.all()
    return render(request, 'contactsapp/index.html', {'contacts': contacts})


def create(request):
    return render(request, 'contactsapp/create.html', {})


def save(request):
    contact_name = request.POST['contact_name']
    contact_birthday = request.POST['contact_birthday']
    contact_favorite_number = request.POST['contact_favorite_number']
    contact_favorite_fruit = request.POST['contact_favorite_fruit']
    contact_favorite_color = request.POST['contact_favorite_color']

    contact = Contact(name=contact_name,
                      birthday=contact_birthday,
                      favorite_number=contact_favorite_number,
                      favorite_fruit=contact_favorite_fruit,
                      favorite_color=contact_favorite_color)
    contact.save()

    return HttpResponseRedirect(reverse('contactsapp:index'))


def delete(request):
    contact_id = request.POST['contact_id']
    contact = Contact.objects.get(pk=contact_id)
    contact.delete()
    return HttpResponseRedirect(reverse('contactsapp:index'))

4 Django/solutions/mysite/contactsapp/templates/contactsapp/base.html
<head>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"/>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

</head>


<body>
    {% block content %}{% endblock %}
</body>

4 Django/solutions/mysite/contactsapp/templates/contactsapp/create.html
{% extends 'contactsapp/base.html' %}

<!--<style>-->
<!--form {-->
<!--display:flex;-->
<!--flex-direction:column;-->
<!--width:100px;-->
<!--}-->
<!--</style>-->

<!--<form method="post">-->
    <!--<input type="text" name="contact_name"/>-->
    <!--<label>Birthday</label>-->
    <!--<input type="date" name="contact_birthday"/>-->
    <!--<input type="number" name="contact_favorite_number"/>-->
    <!--<input type="text" name="contact_favorite_fruit"/>-->
    <!--<input type="color" name="contact_favorite_color"/>-->

<!--</form>-->


{% block content %}

<div class="row">
    <form class="col s12" action="{% url 'contactsapp:save' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s6">
                <input id="contact_name" type="text" name="contact_name">
                <label for="contact_name">Name</label>
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                <label for="contact_birthday">Birthday</label>
                <input id="contact_birthday" type="date" name="contact_birthday">
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input id="contact_favorite_number" type="number" name="contact_favorite_number">
                <label for="contact_favorite_number">Favorite Number</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input id="contact_favorite_fruit" type="text" name="contact_favorite_fruit">
                <label for="contact_favorite_fruit">Favorite Fruit</label>
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                <label for="contact_favorite_color">Favorite Color</label>
                <input id="contact_favorite_color" type="color" name="contact_favorite_color">
            </div>
        </div>
        <button type="submit" class="waves-effect waves-light btn">Create Contact</button>
    </form>
</div>

{% endblock %}

4 Django/solutions/mysite/contactsapp/templates/contactsapp/index.html
{% extends 'contactsapp/base.html' %}
{% block content %}




<table>
    <tr>
        <th></th>
        <th>Name</th>
        <th>Birthday</th>
        <th>Age</th>
        <th>Favorite Number</th>
        <th>Favorite Fruit</th>
        <th>Favorite Color</th>
    </tr>
    {% for contact in contacts %}
    <tr>
        <td>
            <form action="{% url 'contactsapp:delete' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="contact_id" value="{{contact.id}}"/>
                <button class="btn-floating btn-large waves-effect waves-light red" type="submit">✗</button>
            </form>
        </td>
        <td>{{contact.name}}</td>
        <td>{{contact.birthday}}</td>
        <td>{{contact.age}}</td>
        <td>{{contact.favorite_number}}</td>
        <td>{{contact.favorite_fruit}}</td>
        <td>{{contact.favorite_color}}</td>
    </tr>
    {% endfor %}

    <!--<script>-->
        <!--let csrf_token = '{{csrf_token}}';-->
        <!--alert(csrf_token);-->
    <!--</script>-->

</table>

<div style="text-align:center">
<a href="{% url 'contactsapp:create' %}" class="waves-effect waves-light btn">Create Contact</a>
</div>
{% endblock %}