4 Django/solutions/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('todos/', include('todoapp.urls')),
    path('todosajax/', include('todoajax.urls')),
    path('contacts/', include('contactsapp.urls')),
    path('contactcbv/', include('contactcbv.urls'))
]

4 Django/solutions/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

4 Django/solutions/mysite/todoapp/urls.py
from django.urls import path

from . import views

app_name = 'todoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('savetodo/', views.savetodo, name='savetodo'),
    path('completetodo/', views.completetodo, name='completetodo'),
    path('completetodoq/', views.completetodoq, name='completetodoq'),
    path('completetodop/<int:todo_id>/', views.completetodop, name='completetodop')
]

4 Django/solutions/mysite/todoapp/models.py
from django.db import models

from django.utils import timezone

class TodoItem(models.Model):
    text = models.CharField(max_length=200)
    completed_date = models.DateTimeField(null=True, blank=True)
    #completd = models.BooleanField()

    def completed(self):
        return self.completed_date is not None

    def complete(self):
        self.completed_date = timezone.now()

    def __str__(self):
        return self.text

4 Django/solutions/mysite/todoapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect

from .models import TodoItem


def index(request):

    todos = TodoItem.objects.filter(completed_date__isnull=True)
    todos_completed = TodoItem.objects.filter(completed_date__isnull=False)
    # todos_completed = TodoItem.objects.filter(completed=False)

    context = {'todos': todos, 'todos_completed': todos_completed}
    return render(request, 'todoapp/index.html', context)



def savetodo(request):
    todo_text = request.POST['todo_text']
    todo_item = TodoItem(text=todo_text, completed_date=None)
    todo_item.save()
    return HttpResponseRedirect(reverse('todoapp:index'))


def completetodo(request):
    todo_id = request.POST['todo_id']
    todo_item = TodoItem.objects.get(pk=todo_id)
    todo_item.complete()
    todo_item.save()
    return HttpResponseRedirect(reverse('todoapp:index'))
    #return HttpResponse('ok')



# complete the todo using the query string
def completetodoq(request):
    todo_id = request.GET['todo_id']
    todo_item = TodoItem.objects.get(pk=todo_id)
    todo_item.complete()
    todo_item.save()
    return HttpResponseRedirect(reverse('todoapp:index'))


# complete the todo using the path
def completetodop(request, todo_id):
    todo_item = TodoItem.objects.get(pk=todo_id)
    todo_item.complete()
    todo_item.save()
    return HttpResponseRedirect(reverse('todoapp:index'))


# def average(*nums):
#     total = 0
#     for num in nums:
#         total += num
#     return total / len(nums)
#
# average([1, 2, 3])
# average(1, 2, 3)
#
#
#
# def movie_ratings(**movie_ratings):
#     for movie in movie_ratings:
#         print(movie + ': ' + str(movie_ratings[movie]))
#
# movie_ratings(batman=5, the_room=2)

4 Django/solutions/mysite/todoapp/templates/todoapp/index.html
<h1>Todos</h1>



<form action="{% url 'todoapp:savetodo' %}" method="post">
    {% csrf_token %}
    <input name="todo_text" type="text"/>
    <button type="submit">add</button>
</form>


<form action="{% url 'todoapp:completetodo' %}" method="post" id="myform">
{% csrf_token %}
<table>
    {% for todo in todos %}
    <tr>
        <td>{{todo.text}}</td>
        <td>

            <!--complete by posting (data will be in the body of the request-->
            <!--<form action="{% url 'todoapp:completetodo' %}" method="post">-->
                <!--{% csrf_token %}-->
                <!--<input type="hidden" name="todo_id" value="{{todo.id}}"/>-->
                <!--<button>✓</button>-->
            <!--</form>-->

            <!--complete by passing a parameter in the query string-->
            <!--<button type="submit" formaction="{% url 'todoapp:completetodoq' %}?todo_id={{todo.id}}">✓</button>-->

            <!--complete by passing a parameter in the path-->
            <!--<button type="submit" formaction="{% url 'todoapp:completetodop' todo.id %}">✓</button>-->

            <input data-todo_id="{{todo.id}}" class="cb" type="checkbox"/>

        </td>
    </tr>
    {% endfor %}
</table>

<script>
    let cbs = document.querySelectorAll('.cb');
    for (let i=0; i<cbs.length; ++i) {
        cbs[i].onchange = function() {
            let todo_id = this.dataset.todo_id;
            // let myform = document.querySelector('#myform');

            // let hi = document.createElement('input');
            // hi.setAttribute('type', 'hidden');
            // hi.setAttribute('name', 'todo_id');
            // hi.setAttribute('value', todo_id);
            // myform.appendChild(hi);
            // myform.submit();


            // we can also do this by changing the location
            window.location = "{% url 'todoapp:completetodoq' %}?todo_id=" + todo_id;
        }
    }
</script>

</form>

<ul style="text-decoration:line-through">
    {% for todo in todos_completed %}
    <li>{{todo.text}}</li>
    {% endfor %}
</ul>