4 Django/solutions/notesproj/notesapp/urls.py
from django.urls import path
# from django.conf.urls import handler400, handler403, handler404, handler500
#
# handler400 = 'my_app.views.bad_request'
# handler403 = 'my_app.views.permission_denied'
# handler404 = 'my_app.views.page_not_found'
# handler500 = 'my_app.views.server_error'

from . import views

app_name = 'notesapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:note_id>/', views.detail, name='detail'),
    path('savenote/', views.savenote, name='savenote'),
    path('createnotepage/', views.create_note_page, name='createnotepage'),
    path('createnote/', views.createnote, name='createnote')
]

4 Django/solutions/notesproj/notesproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notesapp.urls'))
]

4 Django/solutions/notesproj/notesapp/models.py
from django.db import models


# font
# history

class Note(models.Model):
    name = models.CharField(max_length=100)
    body = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + ': ' + self.body

4 Django/solutions/notesproj/notesapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404

from .models import Note


def index(request):
    notes = Note.objects.order_by('-edit_date')
    context = {'notes': notes}
    return render(request, 'notesapp/index.html', context)


def detail(request, note_id):
    #note = Note.objects.get(pk=note_id)
    note = get_object_or_404(Note, pk=note_id)
    context = {'note': note}
    return render(request, 'notesapp/detail.html', context)


def savenote(request):
    note_id = request.POST['note_id']
    note_name = request.POST['note_name']
    note_body = request.POST['note_body']
    note = Note.objects.get(pk=note_id)
    note.name = note_name
    note.body = note_body
    note.save()
    return HttpResponseRedirect(reverse('notesapp:index'))


def create_note_page(request):
    return render(request, 'notesapp/create.html')


def createnote(request):
    note_name = request.POST['note_name']
    note_body = request.POST['note_body']
    note = Note(name=note_name, body=note_body)
    note.save()
    return HttpResponseRedirect(reverse('notesapp:index'))

4 Django/solutions/notesproj/notesapp/templates/notesapp/create.html
<h1>Create Note</h1>

<form id="container" action="{% url 'notesapp:createnote' %}" method="post">
    {% csrf_token %}
    <div>
        <div>
            <label for="note_name_input">Name</label>
        </div>
        <input id="note_name_input" name="note_name" type="text"/>
    </div>
    <div>
        <div>
        <label for="note_body_input">Body</label>
        </div>
        <textarea id="note_body_input" name="note_body"></textarea>
    </div>
    <button type="submit">save</button>
</form>

<style>
    #container > div {
        margin:10px;
    }
</style>

4 Django/solutions/notesproj/notesapp/templates/notesapp/detail.html
<h1>Edit Note</h1>

<form id="container" action="{% url 'notesapp:savenote' %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{note.id}}" name="note_id"/>
    <div>
        <div>
            <label for="note_name_input">Name</label>
        </div>
        <input id="note_name_input" name="note_name" type="text" value="{{note.name}}"/>
    </div>
    <div>
        <div>
        <label for="note_body_input">Body</label>
        </div>
        <textarea id="note_body_input" name="note_body">{{note.body}}</textarea>
    </div>
    <button type="submit">save</button>
</form>



<style>
    #container > div {
        margin:10px;
    }
</style>

4 Django/solutions/notesproj/notesapp/templates/notesapp/index.html
<style>
    td {
        padding: 4px;
    }
</style>

<h1>My Note-Taking App</h1>
<hr/>
<a href="{% url 'notesapp:createnotepage' %}">create new note</a>
<table>
    <tr>
        <th></th>
        <th>Note</th>
        <th>Edited</th>
        <th>Created</th>
    </tr>
    {% for note in notes %}
    <tr>
        <td><a href="{% url 'notesapp:detail' note.id %}">edit</a></td>
        <td>{{note.name}}</td>
        <td>{{note.edit_date}}</td>
        <td>{{note.created_date}}</td>
    </tr>
    {% endfor %}
</table>